### ISSUE TITLE
Usage example?

### ISSUE THREAD

**Issue by dmitshur** [jbardin/gotrace#3]
It'd be great to have an example for how to use gotrace in the README. Right now it just says `usage: gotrace [flags] [path ...]`, but it's a little unclear.

What is path, exactly? Is it an import path of a Go package? Or individual .go files? From looking at the source and trying this package, I can see it's the latter, but I think it'd be nice to have an example that shows how to use gotrace.

Otherwise, this is looking like a great package! I used it today.

**Comment by jbardin** [comment]
Thanks, glad it helped!

I wanted to have it work on import paths too, but haven't gotten around to it. I'll add an example for the current usage.
